In [1]:
import numpy as np

In [2]:
x = np.arange(1000000)

In [3]:
%timeit x ** 2

6.07 ms ± 691 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [4]:
def square_loop(x):
    result = []

    for value in x:
        result.append(value ** 2)

    return result

In [5]:
%timeit square_loop(x)

573 ms ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [6]:
def square_numpy(x):
    return x ** 2

In [7]:
%timeit square_numpy(x)

7.49 ms ± 512 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Method	Time
Python loop	Your result
NumPy vectorization	Your result

Which implementation was faster?
The NumPy vectorized implementation was faster.

How many times faster was it?
The NumPy implementation was approximately 76.5 times faster than the Python loop implementation.

Why might NumPy be faster?
NumPy uses optimized compiled code and avoids the overhead of Python loops, making computations much more efficient.

In [8]:
x1 = np.arange(100)
x2 = np.arange(10000)
x3 = np.arange(1000000)

In [9]:
%timeit x1 ** 2

1.99 μs ± 335 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [10]:
%timeit x2 ** 2

20.3 μs ± 3.85 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [11]:
%timeit x3 ** 2

7.67 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

How does running time change?
As the size of the dataset increases, the running time increases because more elements must be processed. `

In [12]:
data = np.random.normal(size=1000000)

In [13]:
%timeit np.mean(data)

2.24 ms ± 625 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [14]:
%timeit np.std(data)

13.4 ms ± 3.23 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [15]:
%timeit np.sum(data)

2.04 ms ± 414 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Which operation is fastest?
The fastest operation was np.sum(data), which took approximately 2.04 ms per loop.

Why should performance be measured rather than assumed?
Performance depends on the computer hardware, software environment, and implementation details. Benchmarking provides actual measurements instead of assumptions.

In [1]:
import pandas as pd

results = pd.DataFrame({
    "Method": ["Python Loop", "NumPy Vectorization"],
    "Time": ["573 ms", "7.49 ms"]
})

results

                Method     Time
0          Python Loop   573 ms
1  NumPy Vectorization  7.49 ms

In [3]:
import pandas as pd

stats_results = pd.DataFrame({
    "Operation": ["np.mean()", "np.std()", "np.sum()"],
    "Time": ["2.24 ms", "13.4 ms", "2.04 ms"]
})

stats_results

   Operation     Time
0  np.mean()  2.24 ms
1   np.std()  13.4 ms
2   np.sum()  2.04 ms